config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "products#index"
  resources :suppliers
  
  resources :products

  
  post '/orders', to: 'orders#create'
  get '/orders/:id', to: 'orders#show'
  patch '/orders/:id/edit', to: 'orders#update'

  get '/carted_products', to: 'carted_products#index'
  post '/carted_products', to: 'carted_products#create'
  get '/carted_products/:id', to: 'carted_products#show'
  delete '/carted_products/:id', to: 'carted_products#destroy'

end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
  has_many :products
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController


  def index
    @suppliers = Supplier.all
  end

  def new
    @supplier = Supplier.new
  end

  def create
    @supplier = Supplier.new(supplier_params)
    if @supplier.save
      redirect_to "/suppliers/#{@supplier.id}"
    else
      render :new
    end
  end

  def show
    @supplier = Supplier.find_by(id: params[:id])
  end

  def edit
    @supplier = Supplier.find_by(id: params[:id])
  end

  def update
    @supplier = Supplier.find_by(id: params[:id])
    if @supplier.update(supplier_params)
      redirect_to "/suppliers/#{@supplier.id}"
    else
      render :edit
    end
  end

  def destroy
    Supplier.find_by(id: params[:id]).update(active: false)
    redirect_to "/suppliers"
  end

private

  def supplier_params
    params.require(:supplier).permit(:name, :email, :phone, :first_name, :last_name)
  end

end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/suppliers/_form.html.erb
<%= form_for @supplier do |f| %> 
  <div>
    <%= f.label :company_name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
 
  <div>
    <%= f.label :phone_number %>
    <%= f.text_field :phone %>
  </div>
  <div>
    <%= f.label :email_address %>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/suppliers/edit.html.erb
<h1>As a new supplier, please enter your information:</h1>

<%= render "form" %>

app/views/suppliers/index.html.erb
<h1>Supplier list</h1>
<% @suppliers.each do |supplier| %>
<ul>
  <li><%= supplier.first_name  %></li>
  <li><%= supplier.last_name  %></li>
  <li><%= supplier.name  %></li>
  <li><%= supplier.email  %></li>
  <li><%= supplier.phone  %></li>
  <li><%= supplier.active  %></li>

</ul>
<% end %>

app/views/suppliers/new.html.erb
<h1>As a new supplier, please enter your information:</h1>

<%= render "form" %>

app/views/suppliers/show.html.erb
<h1>Supplier Info</h1>
<p>Supplier Number: <%= @supplier.id %></p>
<p>First Name: <%= @supplier.first_name %></p>
<p>Last Name: <%= @supplier.last_name %></p>
<p>Company Name: <%= @supplier.name %></p>
<p>Email: <%= @supplier.email %></p>
<p>Phone: <%= @supplier.phone %></p>
<p>Active: <%= @supplier.active %></p>

<p><%= link_to "Edit Supplier Information", edit_supplier_path %></p>
<p><%= link_to "Remove Supplier", "/suppliers/#{@supplier.id}", method: :delete %></p>